Repository ISPP-12/SarandONGa, pull requests merged in 2023-05, with the labels that each got.

#749 FEAT(#720): ADD CODACY BADGES TO README
  README.md
Labels: ppl, developing

#753 FIX(#729): FIX DELETE PROJECT LINK
  main/templates/project/list.html
  requirements.txt
Labels: ppl, developing

#757 FIX(#729): FIX ACTIONS
  main/templates/project/list.html
  requirements.txt
Labels: bug, ppl, developing

#751 FIX(#721): FIX VIDESSUR LOGO IMG
  main/templates/index/index-videssur.html
Labels: bug, ppl, developing

#754 FIX(#725): FIX DELETE PERSON LINK
  main/templates/components/card-list.html
  main/templates/person/users/list.html
Labels: bug, ppl, developing

#752 FIX(#728): FIX DELETE STOCK LINK
  home/forms.py
  main/templates/stock/list.html
  payment/forms.py
  person/forms.py
  project/forms.py
  stock/forms.py
  subsidy/forms.py
Labels: bug, ppl, developing

#763 FIX(#726): FIX PRICING LINKS
  main/templates/index/index-asem.html
  main/templates/index/index-videssur.html
  main/templates/index/index.html
  main/views.py
Labels: bug, ppl, developing

#761 FIX(#733): FIX DELETE PROJECT LINK MOBILES
  main/templates/project/list.html
Labels: bug, ppl, developing

#765 FIX(#741): SHOW INFO ON MULTIPLE SELECT INPUTS
  main/templates/sponsorship/sponsorship_form.html
Labels: ppl, developing

#764 FIX(#737): ADD ERROR MESSAGES TO FORMS
  main/templates/payment/payment_form.html
  main/templates/service/service_form.html
  main/templates/stock/register.html
  main/templates/subsidy/create.html
Labels: bug, ppl, developing

#762 FIX(#742): FIX WHOLE APP STYLING
  main/templates/components/button.html
  main/templates/components/inputs.html
  main/templates/donation/list.html
  main/templates/home/home_form.html
  main/templates/home/list.html
  main/templates/layouts/master_sidebar.html
  main/templates/payment/payment_form.html
  main/templates/payment/payment_form_malo.html
  main/templates/person/users/list.html
  main/templates/project/list.html
  main/templates/project/project_details.html
  main/templates/stock/list.html
  main/templates/subsidy/list.html
  payment/test_view.py
  payment/views.py
  service/forms.py
  service/views.py
  static/styles/card-list.css
  static/styles/components/button.css
  static/styles/components/input.css
  static/styles/components/pagination.css
  static/styles/components/title.css
  static/styles/master_sidebar.css
Labels: bug, ppl, developing

#755 FIX(#734): PAYMENT FORM NOT MANTAINING SUBJECT
  payment/test_view.py
  payment/views.py
  service/forms.py
  service/views.py
Labels: bug, ppl, developing

#766 FIX(#723): FIX FILTERS
  person/views.py
Labels: bug, ppl, developing

#769 TEST(#726): ADD EXPLORATORY TEST FOR PRICING PLANS
  main/tests.py
Labels: ppl, developing

#760 FIX(#740): FIX CONTACT VIDESSUR LINKS
  main/templates/index/index-asem.html
  main/templates/index/index-videssur.html
Labels: developing

#768 TEST(#745): ADD LOAD TEST WITH LOCUST
  main/load_test.py
Labels: ppl, developing

#770 FIX(#732): FIX DELETE HOME LINKS AND CREATE EXPLORATORY TEST
  home/test_view.py
  main/templates/home/list.html
  main/tests.py
Labels: developing

#771 FIX(DEVELOP): FIX CODACY ISSUES
  main/load_test.py
  main/tests.py
  payment/views.py
  service/forms.py
  static/styles/components/input.css
  static/styles/master_sidebar.css
Labels: ppl, developing
