Repository ISPP-12/SarandONGa, pull requests merged in 2023-04, with the labels that each got.

#536 TEST(#333): TEST REGISTER VIEW FROM STOCK
  main/templates/stock/list.html
  main/templates/stock/register.html
  stock/tests.py
Labels: frontend, sprint 3

#537 FEAT(#456): ASEM USER FILTER COMPLETED
  main/templates/components/search.html
  main/templates/users/list.html
  person/forms.py
  person/views.py
Labels: backend, backend1, sprint 3

#540 FEAT(#429): PAGINATE ASEM USER
  main/templates/users/list.html
  person/views.py
Labels: backend, backend2, sprint 3

#542 FEAT(#432): PAGINATE VOLUNTEER LIST
  person/views.py
Labels: backend, backend2, sprint 3

#539 TEST(#337): ADD DONATIONS VIEW TESTS
  donation/tests.py
  main/templates/donation/list.html
Labels: frontend

#544 FEAT(#428): ADD PROJECT FILTERS
  main/templates/project/list.html
  project/forms.py
  project/views.py
Labels: backend, backend2, sprint 3

#559 FEAT(#463): ADD LIST TABLES HEADERS
  main/templates/components/card-list.html
  main/templates/donation/list.html
  main/templates/home/list.html
  main/templates/project/list.html
  main/templates/subsidy/list.html
  main/templates/users/list.html
  static/styles/card-list.css
  static/styles/master_sidebar.css
Labels: frontend, sprint 3

#548 FEAT(#025): ADD FILTERS FOR THE LIST OF WORKERS
  main/templates/users/list.html
  person/forms.py
  person/views.py
Labels: backend, backend2, sprint 3

#541 FEAT(#435): PAGINATE DONATION LIST
  donation/views.py
  main/templates/donation/list.html
Labels: backend, backend2, sprint 3

#558 FIX(#462): STRAIGHTEN PAYMENT'S LATERAL PANEL
  main/templates/layouts/master_clean_sidebar.html
  main/templates/payment/payment_form.html
Labels: frontend, sprint 3

#580 FEAT(#438): ADD DOCUMENT TO DONATIONS
  SarandONGa/settings.py
  SarandONGa/urls.py
  donation/forms.py
  donation/models.py
  donation/tests.py
  donation/views.py
  main/templates/donation/create.html
  main/templates/donation/list.html
  media/.gitkeep
Labels: backend, backend2, sprint 3

#582 FEAT(#571): REVIEW PERSON ATTRIBUTES AND VALIDATIONS
  SarandONGa/urls.py
  main/templates/components/card-list.html
  main/templates/donation/list.html
  main/templates/users/list.html
  person/models.py
  person/tests_asem_user.py
  person/tests_volunteer.py
Labels: backend, backend2, sprint 3

#586 FEAT(#336): CREATE USER FORM VIEW TESTS
  main/templates/asem_user/asem_user_form.html
  main/templates/components/button.html
  main/templates/components/card-list.html
  main/templates/stock/list.html
  main/templates/users/list.html
  person/tests_asem_user_views.py
  stock/tests.py
Labels: frontend

#583 TEST(#459): ADD SUBSIDY LIST VIEW TEST
  main/templates/subsidy/list.html
  subsidy/tests.py
Labels: frontend, sprint 3

#584 FEAT(#573): NEW SPONSORSHIP VALIDATIONS AND SOLVE MEDIA DOCUMENT ERROR
  SarandONGa/settings.py
  SarandONGa/urls.py
  main/templates/sponsorship/sponsorship_form.html
  sponsorship/forms.py
  sponsorship/models.py
  sponsorship/tests.py
  sponsorship/views.py
Labels: backend, backend2, sprint 3

#614 FEAT(#433): CREATE PAGINATION FOR CHILD LIST
  person/tests_asem_user_views.py
  person/views.py
Labels: backend, backend2, sprint 3

#550 FEAT(#431): PAGINATE PAYMENT LIST
  main/templates/payment/payment_list.html
  payment/views.py
Labels: backend, backend2, sprint 3

#545 FEAT(#436): CREATE AGE ALERT CHILDS
  SarandONGa/context_processors.py
  SarandONGa/settings.py
  donation/views.py
  main/templates/layouts/master.html
  main/views.py
  person/urls.py
  person/views.py
  project/views.py
  sponsorship/views.py
  stock/views.py
  subsidy/views.py
Labels: backend, backend2, sprint 3

#361 FEAT(#281): UPDATE SERVICE
  main/templates/service/service_form_test.html
  main/templates/service_list.html
  service/models.py
  service/urls.py
  service/views.py
Labels: backend, backend1, sprint 2

#420 FEAT(#319): CREATE UPDATE CHILD TESTS
  person/tests_child.py
Labels: backend, backend1, sprint 2

#588 FEAT(#565): REVISION STOCK MODEL
  main/templates/stock/register.html
  stock/forms.py
  stock/models.py
  stock/tests.py
Labels: backend, backend1, sprint 3

#622 FIX(#438): FIX IMAGES AND DOCS
  SarandONGa/settings.py
  SarandONGa/urls.py
  donation/models.py
  main/templates/donation/list.html
  main/templates/person/godfather/form.html
Labels: backend, backend2, sprint 3

#549 FEAT(#019): ADD FILTERS FOR CHILDREN LIST
  person/forms.py
  person/views.py
  requirements.txt
Labels: backend, backend2, sprint 3

#547 FEAT(#480): SUBSIDY FILTER
  main/templates/subsidy/list.html
  subsidy/forms.py
  subsidy/views.py
Labels: backend, backend1

#546 FEAT(#479): PAYMENT FILTER
  main/templates/payment/payment_list.html
  payment/forms.py
  payment/views.py
Labels: backend, backend1

#587 FEAT(#457): ADD USER DETAILS VIEW
  main/templates/asem_user/asem_user_details.html
  main/templates/components/navbar.html
  main/templates/person/child/create_child.html
  main/templates/users/details.html
  main/templates/users/list.html
  person/models.py
  person/urls.py
  person/views.py
  static/favicon.ico
  static/styles/details.css
Labels: frontend

#628 FEAT(#440): CREATE UPDATE PASSWORD FORM
  main/templates/update_password.html
  person/forms.py
  person/urls.py
  person/views.py
Labels: backend, backend2, sprint 3

#590 FEAT(#476): VOLUNTEER FILTER FINISHED
  person/forms.py
  person/views.py
Labels: backend, backend1, sprint 3

#623 FIX(#428): FIX STRING ON FILTER PROJECT FORM
  project/forms.py
Labels: backend, backend2, sprint 3

#632 FEAT(#477): GODFATHER FILTER CREATED
  person/forms.py
  person/views.py
Labels: backend, backend1, sprint 3

#581 FEAT(#563): NEW SUBSIDY ATTRIBUTES
  main/templates/subsidy/create.html
  main/templates/subsidy/list.html
  subsidy/forms.py
  subsidy/models.py
  subsidy/tests.py
Labels: backend, backend1, sprint 3

#421 FEAT(#318): CREATE UPDATE GODFATHER TESTS
  person/tests_godfather.py
Labels: backend, backend1, sprint 2

#629 FIX(#571): SOLVE BUGS IN THE PERSON MODEL
  person/models.py
  person/tests_asem_user_views.py
  person/tests_godfather.py
  person/tests_volunteer.py
  sponsorship/tests.py
Labels: backend, backend2, sprint 3

#633 TEST(#455): ADD PASSWORD UPDATE TESTS
  person/models.py
  person/tests_worker.py
  person/views.py
Labels: backend, backend2, sprint 3

#627 FEAT(#437): ADD SPONSORSHIP FUNCTION
  main/templates/sponsorship/sponsorship_form.html
  main/templates/sponsorship/sponsorship_list.html
  main/templates/users/list.html
  sponsorship/forms.py
  sponsorship/models.py
  sponsorship/tests.py
  sponsorship/views.py
Labels: backend, backend2, sprint 3

#615 TEST(#460): PAYMENT FORM VIEW TESTS
  main/templates/payment/payment_form.html
  payment/test_view.py
  payment/urls.py
  payment/views.py
Labels: frontend, sprint 3

#636 FEAT(#427): FILTER STOCK PRODUCTS
  main/templates/project/list.html
  main/templates/stock/list.html
  stock/forms.py
  stock/views.py
Labels: backend, backend2, sprint 3

#625 FEAT(#561): REVISE DONATION ENTITY
  donation/models.py
  donation/tests.py
Labels: backend, backend1

#641 FIX(#025): FIX FILTERS FOR THE LIST OF WORKERS
  person/forms.py
  person/views.py
Labels: backend, backend2, sprint 3

#635 FEAT(#46): CREATE DONATION FILTER FORM
  donation/forms.py
  donation/views.py
  main/templates/donation/list.html
Labels: backend, backend2, sprint 3

#643 FIX(#437): ADD INITIALIZE FORM FROM DETAILS VIEW
  main/templates/users/details.html
Labels: backend, backend2, sprint 3

#642 FIX(#019): FIX FILTERS FOR THE LIST OF CHILDREN
  person/forms.py
  person/views.py
Labels: backend, backend2, sprint 3

#638 FEAT (#465): ADD INDEX PAGE FOR NGO
  main/templates/index.html
  main/templates/index/index-asem.html
  main/templates/index/index-videssur.html
  main/templates/layouts/master.html
  main/urls.py
  main/views.py
  static/img/ASEM.jpg
  static/img/LOGO-VIDESSUR.png
  static/img/index.png
  static/img/jornada01.jpeg
  static/img/jornada02.jpeg
  static/styles/components/title.css
  static/styles/index.css
Labels: frontend, sprint 2

#649 FIX(#46): FIX PROJECT SEARCH FILTER AND DONATION PAGINATION
  donation/forms.py
  donation/views.py
  main/templates/donation/list.html
  project/forms.py
  project/views.py
  static/img/stock/WhatsApp_Image_2023-01-23_at_11.43.15_2.jpeg
Labels: bug, backend, backend2

#618 TEST(#317): TEST CASE FOR UPDATING SERVICE
  service/tests.py
Labels: backend, backend1, sprint 3

#624 FEAT(#621): EXPORT ASEEM USER EXCEL
  main/templates/layouts/master_sidebar.html
  person/views.py
Labels: backend, backend1, sprint 3

#647 FEAT(#576): REVIEW VOLUNTEER MODEL AND VALIDATORS
  main/templates/users/details.html
  person/forms.py
  person/models.py
  person/tests_volunteer.py
  static/img/person/cuando-el-nino-de-3-anos-no-habla-md.jpg
Labels: backend, backend2, sprint 3

#659 FEAT(#568): SERVICE AMOUNT REVIEWED
  service/models.py
Labels: backend, backend1, sprint 3

#658 FIX(#432): KEEP VOLUNTEER FILTERS WITH PAGINATION
  main/templates/users/list.html
  person/forms.py
  person/views.py
Labels: bug, backend, backend2, sprint 3

#665 FEAT(#575): REVIEW ASEM USER MODEL
  person/models.py
  person/tests_asem_user.py
  person/tests_asem_user_views.py
  person/views.py
Labels: backend, backend2, sprint 3

#664 FIX(#334): FIX MOBILE BUTTONS LINKS
  main/templates/components/card-list.html
Labels: frontend, sprint 3

#630 FEAT(#572): CHANGE NULLABLE OF SOME CHILD'S ATRIBUTES
  person/models.py
  person/tests_child.py
Labels: backend, backend2, sprint 3

#669 FIX(#571): FIX ZIP CODE VALIDATOR
  person/models.py
Labels: bug, backend, backend2, sprint 3

#631 FEAT(#469): FILTER WORKERS FRONTEND
  main/templates/components/search.html
  main/templates/layouts/master_sidebar.html
  main/templates/users/list.html
  person/forms.py
  person/tests_asem_user_views.py
  static/styles/users.css
Labels: frontend, sprint 3

#661 FEAT(#472): ADD UPDATE PASSWORD VIEW
  main/templates/components/navbar.html
  main/templates/update_password.html
  static/styles/login.css
Labels: frontend, sprint 3

#640 FEAT(#567): REVISE PAYMENT ENTITY
  main/templates/payment/payment_form.html
  main/templates/users/list.html
  payment/forms.py
  payment/test_view.py
  payment/views.py
  service/tests.py
Labels: backend, backend1

#673 FEAT(#663): CREATE PRICING VIEW
  main/templates/index.html
  static/styles/index.css
Labels: frontend, sprint 3

#645 FEAT(#560): ADD PAYMENT GATEWAY
  SarandONGa/settings.py
  main/templates/canceled.html
  main/templates/done.html
  main/templates/index.html
  main/templates/process.html
  main/urls.py
  main/views.py
  requirements.txt
Labels: backend, backend1, sprint 3

#644 FEAT(#468): DEAL WITH NULL VALUES IN LIST VIEWS
  donation/views.py
  home/views.py
  main/templates/home/list.html
  main/templates/project/list.html
  person/tests_asem_user_views.py
  person/views.py
  project/views.py
  subsidy/views.py
Labels: frontend

#678 FIX(#475): MAKE USER FORMS DISTINGUISH ATTRS
  main/templates/person/volunteers/register.html
  person/views.py
Labels: frontend, sprint 3

#679 FIX(#567): FIX PAYMENT MODEL AND VIEWS
  main/templates/payment/payment_form.html
  payment/forms.py
  payment/models.py
  payment/views.py
Labels: backend, backend2, sprint 3

#677 FIX(#651): SOLVE LOGIN + LAYOUT + SOME IMAGES ERRORS
  main/templates/components/card-list.html
  main/templates/donation/list.html
  main/templates/home/list.html
  main/templates/person/users/details.html
  main/templates/person/users/list.html
  main/templates/person/workers/register.html
  main/templates/project/list.html
  main/templates/registration/login.html
  main/templates/subsidy/list.html
  static/img/person/Mockup_anuncio.jpg
  static/img/person/Mockup_anuncio_1.jpg
  static/img/person/Mockup_anuncio_1_508O45z.jpg
  static/img/person/Mockup_anuncio_1_F8dnyzM.jpg
  static/img/person/Mockup_anuncio_1_VVjxYdg.jpg
  static/img/stock/smartmockups_lfpucum1_1.png
  static/styles/master_sidebar.css
Labels: frontend

#676 FIX(#652): FIX BUTTONS
  main/templates/components/button.html
  main/templates/components/navbar.html
  main/templates/layouts/master_sidebar.html
  main/templates/person/asem_user/register.html
  main/templates/stock/register.html
  main/templates/users/details.html
  person/views.py
  static/styles/master_sidebar.css
  static/styles/users.css
Labels: frontend, sprint 3

#684 FIX(#663): FIX PRICING TABLES
  main/templates/index.html
  main/templates/index/index-asem.html
  main/templates/index/index-videssur.html
Labels: frontend, sprint 3

#646 FEAT(#646): ALERT IF STOCK IS LOW
  home/views.py
  main/templates/home/list.html
  main/templates/layouts/master.html
  main/templates/subsidy/list.html
  stock/urls.py
  stock/views.py
  subsidy/views.py
Labels: backend, backend1, sprint 3

#683 FEAT(#682): UPDATE ONG PLAN UPON PAYMENT
  main/apps.py
  main/views.py
  ong/models.py
  ong/signals.py
  ong/views.py
Labels: backend, backend2, sprint 3

#660 FIX: REVISION HOME
  home/forms.py
  home/models.py
  home/views.py
  main/templates/home/home_details.html
  main/templates/home/home_form.html
  main/templates/home/list.html
  main/templates/layouts/master.html
  main/templates/subsidy/list.html
Labels: backend, backend1

#589 FEAT(#589): MAIL IF STOCK IS TOO LOW
  .github/workflows/main.yml
  SarandONGa/settings.py
  main/templates/subsidy/list.html
  stock/models.py
Labels: backend, backend1, sprint 3

#681 FEAT(#566): CHECK SERVICE MODEL
  service/models.py
Labels: backend, backend1, sprint 3

#688 FEAT(#687): ADD PRIVACY POLICY FIELDS
  main/templates/person/workers/register.html
  main/templates/registration/login.html
Labels: frontend, sprint 3

#686 FIX(#560): FIX GATEWAY CANCEL PROCESS
  main/templates/canceled.html
Labels: backend, backend1, sprint 3

#668 FEAT(#473): ADD CUSTOM 403 AND 404 ERROR VIEW
  SarandONGa/middleware/__init__.py
  SarandONGa/middleware/custom_404_middleware.py
  SarandONGa/settings.py
  SarandONGa/urls.py
  main/templates/404.html
  main/templates/error/403.html
Labels: frontend, sprint 3

#680 FEAT(#653): ADD VALIDATORS, REMAINING FILTERS AND CONFIRMATIONS
  donation/forms.py
  donation/models.py
  donation/tests.py
  donation/views.py
  home/forms.py
  main/templates/components/card-list.html
  main/templates/components/card.html
  main/templates/components/navbar.html
  main/templates/donation/create.html
  main/templates/donation/list.html
  main/templates/home/home_form.html
  main/templates/home/home_list.html
  main/templates/home/list.html
  main/templates/layouts/master.html
  main/templates/layouts/master_sidebar.html
  main/templates/person/asem_user/register.html
  main/templates/person/godfather/register.html
  main/templates/person/users/list.html
  main/templates/person/workers/register.html
  main/templates/project/list.html
  main/templates/project/register.html
  main/templates/stock/list.html
  main/templates/stock/register.html
  main/templates/subsidy/create.html
  main/templates/subsidy/list.html
  person/forms.py
  person/test_user.py
  person/views.py
  project/forms.py
  stock/forms.py
  stock/models.py
  stock/tests.py
  subsidy/forms.py
  subsidy/tests.py
Labels: frontend, sprint 3

#689 FIX(#652): ADD BUTTONS + CHILD
  person/views.py
Labels: frontend, sprint 3

#671 FEAT(#146): CREATE SERVICE CALENDAR AND FORM VIEW
  main/templates/layouts/master_clean_sidebar.html
  main/templates/payment/payment_form.html
  main/templates/service/service_form.html
  payment/forms.py
  payment/views.py
  service/views.py
  static/styles/calendar_view.css
Labels: frontend, sprint 3

#675 FEAT(#664): CREATE DONWLOAD AS EXCEL FUNCTION FOR CHILDS AND GODFATHERS
  person/models.py
  person/views.py
  requirements.txt
Labels: backend, backend2, sprint 3

#690 FIX(#653): FIX VOLUNTEER MODEL
  person/models.py
Labels: frontend, sprint 3

#715 FIX(develop): FIX VARIOUS ISSUES
  donation/views.py
  home/urls.py
  home/views.py
  main/templates/components/navbar.html
  main/templates/components/pagination.html
  main/templates/donation/list.html
  main/templates/home/list.html
  main/templates/layouts/master_clean_sidebar.html
  main/templates/person/users/details.html
  main/templates/person/users/list.html
  main/templates/person/workers/register.html
  main/templates/project/list.html
  main/templates/stock/list.html
  main/templates/subsidy/list.html
  payment/urls.py
  payment/views.py
  person/forms.py
  person/views.py
  project/forms.py
  project/urls.py
  project/views.py
  service/models.py
  service/urls.py
  service/views.py
  sponsorship/urls.py
  sponsorship/views.py
  static/img/person/WhatsApp_Image_2023-03-31_at_20.44.38.jpeg
  static/img/person/download_16x9.png
  static/img/person/hombre-mira-al-mar-acantilado-al-atardecer_1.jpg
  static/img/person/hombre-mira-al-mar-acantilado-al-atardecer_1_LzgvuKg.jpg
  stock/views.py
  subsidy/views.py
Labels: bug, frontend, backend, sprint 3

#717 FIX(develop): FIX UNIQUE TOGETHER ERROR
  main/templates/layouts/master_sidebar.html
  main/templates/stock/list.html
  person/models.py
  person/views.py
Labels: bug, backend, sprint 3

#720 FIX(#27): FIX USER PHOTO LINK
  main/templates/person/users/list.html
Labels: bug

#719 FEAT(#569) : POPULATE DB BY SCRIPT
  populate.json
  static/img/stock/1349937997_1.jpg
  static/img/stock/418guxXn7ZL.jpg
  static/img/stock/91HM6xsSX-L._AC_SX450_.jpg
  static/img/stock/91maboAiIRL.jpg
  static/img/stock/collier-7-chakras-au-pendentif-en-forme-de-triangle-597_900x.jpg
  static/img/stock/silla-ergonomica-de-oficina-sofia-de-euromof-cabecero-y-brazos-regulables.jpg
Labels: backend, backend1, sprint 3
