Repository ISPP-12/SarandONGa, pull requests merged in 2023-03, with the labels that each got.

#75 FIX(#1): UPDATE REQUIREMENTS FILE
  main/migrations/__init__.py
  requirements.txt
Labels: frontend, backend

#68 FEAT(#64): UPDATE README.MD
  README.md
  main/migrations/__init__.py
  requirements.txt
Labels: document

#85 FEAT(#16): CONFIGURE GITHUB ACTIONS
  .github/workflows/main.yml
  README.md
  SarandONGa/settings.py
  requirements.txt
Labels: backend

#82 FEAT(#4): CREATION OF STOCK MODEL
  .gitignore
  SarandONGa/settings.py
  stock/__init__.py
  stock/admin.py
  stock/apps.py
  stock/migrations/__init__.py
  stock/models.py
  stock/tests.py
  stock/views.py
Labels: backend

#127 CREATE GODFATHER MODEL
  SarandONGa/settings.py
  person/admin.py
  person/migrations/__init__.py
  person/models.py
Labels: backend, backend2

#136 FEAT(#105): CREATE THE ASEM USER MODEL
  person/admin.py
  person/models.py
Labels: backend, backend2

#129 FEAT(#119): CREATION OF SUBSIDY LIST
  SarandONGa/urls.py
  main/templates/subsidy_list.html
  subsidy/views.py
Labels: backend, backend1

#138 FEAT(#109): CREATE ASEM USER LIST FUNCTION
  SarandONGa/urls.py
  main/templates/asem_user_list.html
  person/views.py
Labels: backend, backend2

#149 FEAT(#105): ADD ATTRIBUTES TO THE ASEM USER MODEL
  person/models.py
Labels: backend, backend2

#140 FEAT(#106): CREATION AND FORM FOR ASEM USERS
  SarandONGa/urls.py
  main/templates/asem_user/asem_user_form.html
  person/forms.py
  person/models.py
  person/views.py
Labels: backend, backend2

#154 FEAT(#152): CREATE SELECT + LABEL
  main/templates/components/select.html
  main/templates/index.html
  main/views.py
  static/styles/master.css
Labels: frontend

#142 FEAT(#97): CREATE LABEL + INPUT COMPONENTS
  .gitignore
  SarandONGa/settings.py
  SarandONGa/urls.py
  main/templates/components/inputs.html
  main/templates/donation/list.html
  main/templates/index.html
  main/templates/master.html
  main/urls.py
  main/views.py
  static/styles/donation.css
  static/styles/master.css
Labels: frontend

#157 FIX(#119): FIX LIST SUBCENCY PROBLEMS WITH FRONTEND GROUP
  main/templates/subsidy_list.html
  subsidy/views.py
Labels: backend, backend1

#83 FEAT(#51): CREATE FORM FOR DONATIONS
  Pipfile
  donation/forms.py
  donation/models.py
  donation/tests.py
  donation/urls.py
  donation/views.py
  main/templates/donation_form.html
  main/views.py
Labels: backend, backend2

#156 FIX(#50): ADD ATTRIBUTE TO DONATION MODEL
  donation/models.py
Labels: backend, backend1

#153 FIX(#13): ADD PERMISSIONS TO WORKER
  SarandONGa/settings.py
  person/admin.py
  person/models.py
  person/tests.py
  person/views.py
  requirements.txt
  volunteer/__init__.py
  volunteer/admin.py
  volunteer/apps.py
  volunteer/models.py
  volunteer/tests.py
  volunteer/views.py
Labels: bug, backend, backend2

#158 FEAT(#120): CREATION OF PAYMENT LIST
  SarandONGa/settings.py
  SarandONGa/urls.py
  main/templates/payment/payment_list.html
  payment/migrations/__init__.py
  payment/models.py
  payment/views.py
Labels: backend, backend1

#143 FEAT(#98): CREATE BUTTON COMPONENT
  main/templates/components/button.html
  main/templates/index.html
  main/templates/layouts/master_sidebar.html
  static/styles/components/button.css
Labels: frontend

#162 FEAT( #28 ): ADD WORKER CREATION FORM
  SarandONGa/urls.py
  main/templates/worker/worker_form.html
  person/forms.py
  person/views.py
Labels: backend, backend2

#139 FEAT(#124): CREATE FORM FOR PAYMENTS
  SarandONGa/urls.py
  main/admin.py
  main/models.py
  main/templates/payment/create_donation.html
  main/tests.py
  payment/admin.py
  payment/forms.py
  payment/models.py
  payment/views.py
Labels: backend, backend1

#128 FEAT(#116): CREATE SERVICE MODEL
  SarandONGa/settings.py
  person/models.py
  service/__init__.py
  service/admin.py
  service/apps.py
  service/models.py
  service/tests.py
  service/views.py
Labels: backend, backend2

#167 FEAT(#107): CREATE WORKERS LIST
  Charlie.PNG
  SarandONGa/urls.py
  main/templates/workers.html
  person/urls.py
  person/views.py
Labels: backend, backend2

#172 FIX(#50): FIX SOME ATTRIBUTE VALIDATOR IN MODELS
  donation/models.py
Labels: backend, backend1

#161 FIX(#104): FIX GODFATHER ATRIBUTES AND ADD SLUG ATRIBUTE
  person/models.py
  person/views.py
Labels: backend, backend2

#155 FEAT(#110): CREATE GODFATHER LIST FUNCTION
  SarandONGa/urls.py
  main/templates/person/godfather_list.html
  person/views.py
Labels: backend, backend2

#160 FEAT(#23): CREATION OF CHILD MODEL
  SarandONGa/settings.py
  beneficiary/__init__.py
  beneficiary/admin.py
  beneficiary/apps.py
  beneficiary/migrations/__init__.py
  beneficiary/models.py
  beneficiary/tests.py
  beneficiary/views.py
  person/admin.py
  person/models.py
Labels: backend, backend1

#166 FEAT( #108 ): CREATE SERVICE LIST
  SarandONGa/urls.py
  main/templates/service_list.html
  person/models.py
  person/urls.py
  service/views.py
Labels: backend, backend2

#181 FEAT(#115): CREATE AND FORM SERVICE
  SarandONGa/urls.py
  main/templates/service/service_form.html
  person/models.py
  service/forms.py
  service/migrations/__init__.py
  service/urls.py
  service/views.py
Labels: backend, backend2

#175 FEAT(#54): ADD NEW SUBSIDY ATTRIBUTES
  SarandONGa/urls.py
  subsidy/forms.py
  subsidy/models.py
Labels: backend, backend1

#133 FEAT(#125): CREATE FORM FOR GODFATHER
  SarandONGa/urls.py
  main/templates/godfather_form.html
  person/forms.py
  person/models.py
  person/urls.py
  person/views.py
Labels: backend, backend1

#169 FEAT(#34): CREATE STOCK REGISTER VIEW
  SarandONGa/settings.py
  SarandONGa/urls.py
  main/templates/components/inputs.html
  main/templates/components/select.html
  main/templates/index.html
  main/templates/stock/register.html
  main/urls.py
  main/views.py
  static/img/no_image.PNG
  static/styles/master.css
  stock/views.py
Labels: frontend

#185 FEAT(#24): CREATION OF CHILD FORM
  main/templates/person/child/create_child.html
  person/forms.py
  person/urls.py
  person/views.py
Labels: backend, backend1

#182 FEAT(#95): ADD CARD COMPONENT
  main/templates/components/card-display.html
  main/templates/components/card.html
  main/templates/index.html
  main/views.py
  static/img/img-not-found.png
  static/img/img-not-found.svg
  static/styles/components/cards.css
Labels: frontend

#159 FEAT(#100): ADD TITLE CLASS STYLE
  main/templates/components/title.html
  main/templates/layouts/master_sidebar.html
  static/styles/master.css
  static/styles/master_sidebar.css
Labels: frontend

#170 FEAT(#103): ADD SCRIPT TO GENERATE SIDE PREVIEW COMPONENT
  main/templates/donation/donation_list.html
  main/templates/donation/list.html
  main/templates/index.html
  main/templates/layouts/master_sidebar.html
  static/js/showPreview.js
Labels: frontend

#76 FEAT(#36): CREATE STOCK LIST INTERFACE
  main/templates/components/navbar.html
  main/templates/index.html
  main/templates/layouts/master_full_width.html
  main/templates/stock/list.html
  main/templates/stock/stock_list.html
  static/styles/master.css
  stock/views.py
Labels: frontend

#183 FIX(#105): DELETE DUPLICATE ATTRIBUTES FROM ASEMUser MODEL
  person/models.py
Labels: backend, backend2

#168 FEAT(#147): PAYMENTS VIEW FORM
  main/templates/layouts/master.html
  main/templates/payment/payment_form.html
  main/templates/volunteers/volunteers_form.html
  payment/views.py
  static/styles/components/button.css
  static/styles/components/input.css
  static/styles/master.css
Labels: frontend

#148 FEAT(#121): CREATION OF VOLUNTEER LIST
  SarandONGa/urls.py
  main/templates/volunteers.html
  person/urls.py
  person/views.py
Labels: backend, backend1

#173 FEAT(#27): CRETE USER LIST VIEW
  12.graf.PNG
  12.graf_SAlVFNC.PNG
  12_grag_n.PNG
  12_grag_n_Mgu8DIW.PNG
  SarandONGa/urls.py
  edt.PNG
  main/templates/components/card-list.html
  main/templates/index.html
  main/templates/layouts/master_sidebar.html
  main/templates/users/list.html
  person/urls.py
  person/views.py
  static/img/someone.png
  static/styles/card-list.css
  static/styles/master.css
  static/styles/workers.css
Labels: frontend

#180 FEAT(#111): LIST CHILDREN
  main/templates/children_list.html
  person/models.py
  person/urls.py
  person/views.py
Labels: backend, backend2

#190 FIX(#188): MERGE FEATURE BACKEND + FRONTEND
  SarandONGa/urls.py
  donation/urls.py
  donation/views.py
  main/templates/asem_user/asem_user_form.html
  main/templates/components/card-list.html
  main/templates/components/inputs.html
  main/templates/components/navbar.html
  main/templates/godfather_form.html
  main/templates/layouts/master_sidebar.html
  main/templates/person/child/create_child.html
  main/templates/stock/list.html
  main/templates/stock/register.html
  main/templates/users/list.html
  payment/urls.py
  payment/views.py
  person/urls.py
  person/views.py
  service/urls.py
  service/views.py
  stock/forms.py
  stock/urls.py
  stock/views.py
  subsidy/urls.py
  subsidy/views.py
Labels: frontend, backend

#151 FEAT(#102): CREATE SEARCH COMPONENT
  donation/views.py
  main/templates/components/search.html
  main/templates/donation/list.html
  main/templates/index.html
  main/templates/layouts/master_sidebar.html
  main/templates/person/godfather_list.html
  main/templates/stock/list.html
  main/templates/subsidy_list.html
  main/views.py
  payment/views.py
  person/views.py
  service/views.py
  stock/views.py
  subsidy/views.py
Labels: frontend

#192 TEST(#74):CHILD CREATE TEST
  person/models.py
  person/tests.py
Labels: backend, backend1

#191 TEST(#114): PERSON AND ASEMUSER CREATE TEST
  person/tests.py
Labels: backend, backend2

#196 FEAT(#112): TEST SERVICE CREATION
  payment/__init__.py
  person/__init__.py
  person/tests_asem_user.py
  person/tests_child.py
  service/models.py
  service/tests.py
Labels: backend, backend2

#195 FEAT(#178): STOCK TESTS PERFORMED
  stock/tests.py
Labels: backend, backend1

#197 FEAT(#70): TEST CREATE DONATION
  donation/tests.py
Labels: backend, backend2

#198 TEST(#18): WORKER CREATION TESTS
  person/tests_worker.py
Labels: backend, backend2

#201 TEST(#126): CREATE CREATION GODFATHER TEST
  person/models.py
  person/tests_godfather.py
Labels: backend, backend1

#194 TEST(#123): TEST PAYMENT CREATION
  payment/tests.py
Labels: backend, backend1

#247 FIX(#69): SOLVE PROBLEMS CAUSED BY MODEL UPDATE
  subsidy/models.py
  subsidy/tests.py
Labels: backend, backend2

#232 TEST(#226): CREATE AND UPDATE TEST STOCK
  stock/models.py
  stock/tests.py
Labels: backend, backend2

#293 FEAT(206): DELETE SUBSIDIES
  main/templates/subsidy_form.html
  subsidy/forms.py
  subsidy/models.py
  subsidy/urls.py
  subsidy/views.py
Labels: backend, backend2

#296 FEAT(#255): FIX DATE IN FORMS
  donation/forms.py
  main/templates/donation_form.html
  payment/forms.py
  person/forms.py
  person/models.py
  person/tests_child.py
  service/forms.py
  subsidy/forms.py
Labels: backend, backend2

#255 FEAT(#233): CREATE CSS PALETTE. APPLY IT TO THE PROJECT
  main/templates/donation/list.html
  static/styles/components/button.css
  static/styles/components/cards.css
  static/styles/components/input.css
  static/styles/components/navbar.css
  static/styles/components/title.css
  static/styles/donations.css
  static/styles/master.css
  static/styles/projects.css
  static/styles/stock.css
  static/styles/subsidies.css
  static/styles/workers.css
Labels: frontend

#294 FEAT(#220): GODFATHER DETAILS FUNCTION
  main/templates/prueba_padrino_detalles.html
  person/urls.py
  person/views.py
Labels: backend, backend2

#230 FEAT(#202): CREATE ONG ENTITY
  SarandONGa/settings.py
  donation/models.py
  donation/tests.py
  ong/__init__.py
  ong/admin.py
  ong/apps.py
  ong/migrations/__init__.py
  ong/models.py
  ong/tests.py
  ong/views.py
  person/models.py
  person/tests_asem_user.py
  person/tests_child.py
  person/tests_godfather.py
  person/tests_worker.py
  service/tests.py
  stock/models.py
  stock/tests.py
  subsidy/models.py
  subsidy/tests.py
Labels: backend, backend2

#306 FEAT(#267): TASK RELATED TO HOME MODEL
  SarandONGa/settings.py
  SarandONGa/urls.py
  home/__init__.py
  home/admin.py
  home/apps.py
  home/forms.py
  home/models.py
  home/tests.py
  home/urls.py
  home/views.py
  main/templates/home/home_form.html
  main/templates/home/home_list.html
Labels: backend, backend1

#268 FIX(#236): FIX INPUT COMPONENT EVERYWHERE
  donation/views.py
  main/templates/asem_user/asem_user_form.html
  main/templates/components/inputs.html
  main/templates/donation_form.html
  main/templates/godfather_form.html
  main/templates/payment/payment_form.html
  main/templates/person/child/create_child.html
  main/templates/stock/register.html
  main/templates/subsidy_form.html
  main/templates/volunteers/volunteers_form.html
  main/templates/worker/worker_form.html
  payment/forms.py
  payment/views.py
  person/views.py
  service/views.py
  stock/forms.py
  stock/views.py
  subsidy/views.py
Labels: frontend

#303 FEAT(#278): UPDATE SUBSIDY
  main/templates/subsidy_form.html
  subsidy/urls.py
  subsidy/views.py
Labels: backend, backend1

#301 FEAT(#049): IMPLEMENT DONATION UPDATE FUNCTION
  donation/urls.py
  donation/views.py
  main/templates/donation_form.html
  main/templates/donation_update_form.html
Labels: backend, backend2

#309 FEAT(#10): ADD UPDATE VOLUNTEER FUNCTION
  main/templates/components/card-list.html
  person/urls.py
  person/views.py
Labels: backend, backend2

#311 FEAT(#214): ADD UPDATE ASEM USER FUNCTION
  person/models.py
  person/urls.py
  person/views.py
Labels: backend, backend2

#308 FEAT(#235): FIX CARD-LIST COMPONENT
  main/templates/components/card-list.html
  main/templates/donation/list.html
  main/templates/subsidy/list.html
  main/templates/users/list.html
  static/styles/card-list.css
  static/styles/donations.css
  static/styles/master_sidebar.css
  static/styles/subsidies.css
  static/styles/workers.css
Labels: frontend

#299 TEST(#225): UPDATE DONATION TESTS
  donation/models.py
  donation/tests.py
Labels: backend, backend2

#267 FEAT(#237): ADD EDIT/DELETE BUTTONS AND SEARCH BAR
  main/templates/components/button.html
  main/templates/components/card-display.html
  main/templates/components/card.html
  main/templates/donation/list.html
  main/templates/layouts/master.html
  main/templates/layouts/master_full_width.html
  main/templates/layouts/master_sidebar.html
  main/templates/stock/list.html
  main/templates/stock/register.html
  main/templates/users/list.html
  static/styles/components/button.css
  static/styles/components/cards.css
  static/styles/master_sidebar.css
  static/styles/stock.css
  static/styles/workers.css
  stock/views.py
Labels: frontend

#338 FEAT(#297): GIVE STYLE TO INPUTS
  SarandONGa/urls.py
  donation/forms.py
  donation/models.py
  home/forms.py
  home/models.py
  home/views.py
  main/templates/asem_user/asem_user_form.html
  main/templates/components/inputs.html
  main/templates/donation_form.html
  main/templates/godfather_form.html
  main/templates/home/home_form.html
  main/templates/layouts/master.html
  main/templates/payment/payment_form.html
  main/templates/person/child/create_child.html
  main/templates/service/service_form.html
  main/templates/stock/register.html
  main/templates/subsidy_form.html
  main/templates/volunteers/volunteers_form.html
  main/templates/worker/worker_form.html
  main/urls.py
  ong/models.py
  payment/forms.py
  payment/models.py
  payment/views.py
  person/forms.py
  person/models.py
  service/forms.py
  static/styles/components/input.css
  static/styles/master.css
  stock/forms.py
  stock/models.py
  subsidy/forms.py
  subsidy/models.py
Labels: backend, backend2

#314 FEAT(#270): SPONSORSHIP MODEL, DELETE AND LIST
  SarandONGa/settings.py
  SarandONGa/urls.py
  home/forms.py
  home/migrations/__init__.py
  home/views.py
  main/templates/sponsorship/sponsorship_form.html
  main/templates/sponsorship/sponsorship_list.html
  sponsorship/__init__.py
  sponsorship/admin.py
  sponsorship/apps.py
  sponsorship/forms.py
  sponsorship/migrations/__init__.py
  sponsorship/models.py
  sponsorship/tests.py
  sponsorship/urls.py
  sponsorship/views.py
Labels: backend, backend1, sprint 2

#339 FEATURE(#245): REFACTOR SOME STYLE FILES
  .gitignore
  main/templates/components/navbar.html
  main/templates/users/list.html
  static/styles/master.css
  static/styles/stock.css
  static/styles/users.css
Labels: frontend

#313 FEAT(#208): ADD WORKER DELETE FUNCTION
  person/models.py
  person/urls.py
  person/views.py
Labels: backend, backend2

#310 FEAT(#223): TEST VOLUNTEER CREATION
  person/forms.py
  person/models.py
  person/tests_volunteer.py
Labels: backend, backend2

#302 FIX(#238): PROBLEMS WITH BUTTONS IN LAYOUT SOLVED
  delete.bat
  main/templates/asem_user_list.html
  main/templates/donation/list.html
  main/templates/layouts/master_sidebar.html
  main/templates/subsidy/list.html
  main/templates/users/list.html
Labels: frontend

#355 FEAT(#205): ADD CREATE AND PROYECT FORM
  SarandONGa/urls.py
  main/templates/proyect/proyect_form.html
  proyect/forms.py
  proyect/models.py
  proyect/urls.py
  proyect/views.py
Labels: backend, backend2, sprint 2

#341 FEAT(#14): CREATE WORKER UPDATE FORM
  main/templates/worker/worker_create_form.html
  main/templates/worker/worker_update_form.html
  person/forms.py
  person/urls.py
  person/views.py
Labels: backend, backend2, sprint 2

#360 FEAT(#209): CREATE DELETE ASEM USER FUNCTION
  Charlie.PNG
  person/urls.py
  person/views.py
Labels: backend, backend2, sprint 2

#346 FEATURE(#246): ADD VOLUNTEER FORM
  main/templates/layouts/master_full_width.html
  main/templates/users/list.html
  main/templates/volunteers/volunteers_form.html
  person/forms.py
  person/views.py
Labels: frontend

#366 FEAT(#254): CREATE CALENDAR COMPONENT
  SarandONGa/settings.py
  main/templates/components.html
  main/templates/components/calendar.html
  main/urls.py
  main/views.py
  service/urls.py
  service/views.py
  static/js/calendar.js
  static/styles/components/calendar.css
  static/styles/master.css
Labels: frontend

#376 FIX(104): ADD START AND TERMINATION DATES TO CHILD, GODFATHER AND HOME
  home/forms.py
  home/models.py
  person/forms.py
  person/models.py
  person/tests_child.py
  person/tests_godfather.py
Labels: backend, backend2

#343 FEAT(#249): CREATION OF DONATIONS FORM
  donation/forms.py
  donation/views.py
  main/templates/components/card-list.html
  main/templates/components/title.html
  main/templates/donation/create.html
  main/templates/donation/list.html
  main/templates/layouts/master_full_width.html
  static/styles/components/button.css
Labels: frontend

#350 FEAT(#276): PAYMENT DETAILS FUNCTION DONE
  main/templates/payment/payment_details.html
  payment/urls.py
  payment/views.py
Labels: backend, backend1

#374 FEAT(218): ADD VOLUNTEER DETAILS FUNCTION
  main/templates/volunteer_details.html
  person/urls.py
  person/views.py
Labels: backend, backend2

#385 FEAT(#219): CREATE WORKER DETAILS VIEW
  main/templates/worker/details.html
  person/urls.py
  person/views.py
Labels: backend, backend2, sprint 2

#305 FEAT(#280): UPDATE GODFATHER
  SarandONGa/settings.py
  person/forms.py
  person/models.py
  person/tests_godfather.py
  person/urls.py
  person/views.py
  requirements.txt
Labels: backend, backend1

#304 FEAT(#279): UPDATE CHILD
  person/models.py
  person/urls.py
  person/views.py
Labels: backend, backend1

#351 FEAT(#277): SERVICE DETAILS DONE
  main/templates/service/service_details.html
  service/urls.py
  service/views.py
Labels: backend, backend1

#347 FEATURE(#251): ADD ASEM USER FORM
  main/templates/asem_user/asem_user_form.html
  main/templates/layouts/master_full_width.html
  main/templates/volunteers/volunteers_form.html
  person/forms.py
  person/views.py
Labels: frontend

#340 FEAT(#250): CREATE SUBSIDY FORM
  delete_migrations (1).bat
  main/templates/layouts/master_full_width.html
  main/templates/subsidy/create.html
  ong/models.py
  subsidy/forms.py
  subsidy/models.py
  subsidy/views.py
Labels: frontend

#324 FEAT(#248): ADD WORKER FORM
  .gitignore
  SarandONGa/urls.py
  main/templates/components/button.html
  main/templates/godfather_form.html
  main/templates/index.html
  main/templates/payment/create_donation.html
  main/templates/person/child/create_child.html
  main/templates/stock/list.html
  main/templates/stock/register.html
  main/templates/worker/worker_create_form.html
  main/templates/workers/register.html
  payment/urls.py
  person/forms.py
  person/models.py
  person/views.py
Labels: frontend

#348 FEATURE(#252): ADD CHILD FORM
  main/templates/person/child/create_child.html
  main/templates/volunteers/volunteers_form.html
  person/forms.py
  person/views.py
Labels: frontend

#342 FIX(#177): STOCK FORM NOW INCLUDE ONG
  stock/views.py
Labels: backend, backend1

#387 FEAT(#282): UPDATE HOME
  home/models.py
  home/urls.py
  home/views.py
  main/templates/home/home_form.html
Labels: backend, backend1, sprint 2

#407 FEAT(#2): ADD LOGIN AND AUTHENTICATION ONG
  12.graf.PNG
  12.graf_SAlVFNC.PNG
  12_grag_n.PNG
  12_grag_n_Mgu8DIW.PNG
  SarandONGa/settings.py
  SarandONGa/urls.py
  delete.bat
  delete_migrations (1).bat
  donation/forms.py
  donation/models.py
  donation/views.py
  edt.PNG
  home/forms.py
  home/models.py
  home/urls.py
  home/views.py
  main/templates/components/navbar.html
  main/templates/error/403.html
  main/templates/registration/login.html
  main/templates/service/service_form_backend.html
  main/views.py
  ong/models.py
  payment/forms.py
  payment/models.py
  payment/tests.py
  payment/views.py
  person/forms.py
  person/models.py
  person/tests_godfather.py
  person/urls.py
  person/views.py
  project/forms.py
  project/views.py
  service/forms.py
  service/models.py
  service/tests.py
  service/views.py
  sponsorship/forms.py
  sponsorship/models.py
  sponsorship/urls.py
  sponsorship/views.py
  stock/forms.py
  stock/models.py
  stock/views.py
  subsidy/forms.py
  subsidy/models.py
  subsidy/views.py
Labels: backend, backend2, sprint 2

#377 FIX(#358): CORRECT SOME ENTITIES
  donation/models.py
  donation/views.py
  home/models.py
  ong/models.py
  payment/models.py
  payment/tests.py
  payment/views.py
  person/forms.py
  person/models.py
  person/tests_asem_user.py
  person/tests_child.py
  project/models.py
  service/models.py
  sponsorship/models.py
  stock/models.py
  subsidy/models.py
Labels: backend, backend1

#273 FIX(#199): FIX SAVING IMAGES ON DATABASE
  .gitignore
  main/templates/workers/register.html
  person/forms.py
  person/models.py
  person/views.py
Labels: bug, backend, backend2

#357 TEST(#322): CREATE AND FORMULARY OF HOME
  home/models.py
  home/tests.py
Labels: backend, backend1

#393 FEAT(#221): ADD PROJECT DETAILS FUNCTION
  .gitignore
  main/templates/project/project_details.html
  project/urls.py
  project/views.py
Labels: backend, backend2, sprint 2

#381 FEAT(#287): SERVICE DELETE DONE
  service/urls.py
  service/views.py
Labels: backend, backend1

#382 FEAT(#288): GODFATHER DELETE DONE
  person/urls.py
  person/views.py
Labels: backend, backend1

#383 FEAT(#289): STOCK DELETE DONE
  stock/urls.py
  stock/views.py
Labels: backend, backend1

#384 FEAT(#290): DONATION DELETE DONE
  donation/urls.py
  donation/views.py
Labels: backend, backend1

#386 FEAT(#291): CHILD DELETE DONE
  person/urls.py
  person/views.py
Labels: backend, backend1

#408 FEAT(#332): ADD HOME FORM
  home/forms.py
  main/templates/home/home_form.html
Labels: frontend

#410 FEAT(#329): ADD PROJECT LIST VIEW
  main/templates/components/navbar.html
  main/templates/project/list.html
  project/urls.py
  project/views.py
  static/styles/projects.css
Labels: frontend, sprint 2

#406 FEAT(#253): CREATE PROJECT FORM
  main/templates/project/project_form.html
  main/templates/project/register.html
  person/forms.py
  person/views.py
  project/forms.py
  project/views.py
  static/styles/components/input.css
Labels: frontend, sprint 2

#409 FEAT(#326): ADD LOGIN FORM
  main/templates/components/inputs.html
  main/templates/registration/login.html
  main/views.py
  static/styles/login.css
Labels: frontend

#373 FEAT(#328): CREATE HOME LIST VIEW
  donation/views.py
  home/urls.py
  home/views.py
  main/templates/components/navbar.html
  main/templates/home/list.html
  static/styles/homes.css
Labels: frontend

#353 FEAT(#275): HOME DETAILS DONE
  home/urls.py
  home/views.py
  main/templates/home/home_details.html
Labels: backend, backend1

#394 FEAT(#331): ADD SPONSORSHIP FORM
  .vscode/settings.json
  donation/forms.py
  donation/views.py
  main/templates/asem_user/asem_user_form.html
  main/templates/components/navbar.html
  main/templates/home/home_form.html
  main/templates/person/child/create_child.html
  main/templates/sponsorship/sponsorship_form.html
  main/templates/volunteers/volunteers_form.html
  main/templates/workers/register.html
  payment/forms.py
  person/forms.py
  person/models.py
  project/forms.py
  service/forms.py
  sponsorship/forms.py
  sponsorship/views.py
  stock/forms.py
  subsidy/forms.py
  subsidy/views.py
Labels: frontend

#389 FEAT(#17): ADD TEST UPDATE WORKERS
  person/tests_worker.py
Labels: backend, backend2

#378 FEAT(#228): ADD ATRIBUTE PAID AND PAYMENT UPDATES TESTS
  payment/forms.py
  payment/models.py
  payment/tests.py
Labels: backend, backend2

#412 TEST(#316): UPDATE TEST FOR HOME
  home/tests.py
Labels: backend, backend1, sprint 2

#392 FEAT(#224): TEST CREATE PROJECT
  project/tests.py
Labels: backend, backend2, sprint 2

#402 FEAT(#284): UPDATE SPONSORSHIP
  main/templates/sponsorship/sponsorship_form.html
  sponsorship/forms.py
  sponsorship/models.py
  sponsorship/urls.py
  sponsorship/views.py
Labels: backend, backend1, sprint 2

#396 FEAT(#327): CREATE PAYMENTS FORM
  Nuevo documento de texto.bat
  main/templates/components/title2.html
  main/templates/home/home_form.html
  main/templates/layouts/master_clean_sidebar.html
  main/templates/payment/payment_form.html
  payment/forms.py
  payment/models.py
  payment/views.py
  person/tests_volunteer.py
  static/styles/components/title.css
  static/styles/payment_form.css
Labels: frontend, sprint 2

#417 FIX(#402): FIX UPLOAD PHOTO
  main/templates/stock/register.html
  static/img/stock/Flujo_frontend.png
Labels: frontend

#416 FEAT(#204): RELATION REVISION
  main/templates/payment/payment_form.html
  main/templates/sponsorship/sponsorship_form.html
  main/templates/sponsorship/sponsorship_list.html
  main/templates/subsidy/create.html
  ong/apps.py
  ong/models.py
  payment/forms.py
  payment/models.py
  payment/tests.py
  payment/views.py
  person/forms.py
  person/models.py
  person/tests_child.py
  person/tests_volunteer.py
  service/models.py
  sponsorship/forms.py
  sponsorship/models.py
  sponsorship/tests.py
  sponsorship/urls.py
  sponsorship/views.py
  subsidy/models.py
  subsidy/tests.py
Labels: backend2, sprint 2

#419 FEAT(#320): CREATE UPDATE SUBSIDY TESTS
  sponsorship/tests.py
  subsidy/tests.py
Labels: backend, backend1, sprint 2

#418 TEST(#335): ADD STOCK VIEW TESTS
  main/templates/components/card-display.html
  main/templates/components/card.html
  main/templates/stock/list.html
  requirements.txt
  stock/tests.py
Labels: frontend, sprint 2

#423 FIX(#204): FIX SPONSORSHIP TEST AGAIN
  sponsorship/tests.py
Labels: backend, backend2, sprint 2

#422 TEST(#315): UPDATE SPONSORSHIP
  sponsorship/tests.py
Labels: backend, backend1, sprint 2

#426 FIX(#425): FIX SOME ERROS
  .gitignore
  Nuevo documento de texto.bat
  donation/views.py
  home/views.py
  main/templates/components/navbar.html
  main/templates/layouts/master_clean_sidebar.html
  main/templates/payment/payment_form.html
  main/templates/stock/list.html
  main/templates/stock/register.html
  payment/forms.py
  payment/views.py
  person/views.py
  project/views.py
  sponsorship/views.py
  static/img/person/kurt-von-jNN9eZdPC5M-unsplash.jpg
  static/img/person/kurt-von-jNN9eZdPC5M-unsplash_wh2gSX8.jpg
  static/img/person/randomforest.jpg
  static/img/person/randomforest_4x4Rjon.jpg
  static/img/person/randomforest_WNK5HuY.jpg
  static/img/stock/Flujo_frontend.png
  static/img/stock/Imagen_de_WhatsApp_2023-02-21_a_las_16.42.04.jpg
  static/img/stock/Imagen_de_WhatsApp_2023-03-06_a_las_15.54.39.jpg
  static/img/stock/kurt-von-jNN9eZdPC5M-unsplash.jpg
  static/img/stock/randomforest.jpg
  static/img/worker/randomforest.jpg
  stock/views.py
  subsidy/views.py
Labels: frontend, backend, sprint 2

#411 FEAT(#334): CREATE BUTTONS ON LATERAL PANEL
  main/templates/components/card-list.html
  main/templates/donation/list.html
  main/templates/home/list.html
  main/templates/layouts/master_sidebar.html
  main/templates/project/list.html
  main/templates/subsidy/list.html
  main/templates/users/list.html
  person/tests_volunteer.py
  static/styles/components/navbar.css
  static/styles/master_sidebar.css
Labels: frontend, sprint 2
